### ISSUE TITLE
Add more docs

### ISSUE THREAD

**Issue by Ianyourgod** [ScratchVerifier/ScratchOAuth2#71]
Hello. I'm trying to implement this oauth system, but the only real docs are the getting started. I can't figure out how to do a refresh token or anything else besides just the initial login.

**Comment by Kenny2github** [comment]
Does the [API Reference](https://oauth2.scratch-wiki.info/wiki/API_Reference) address your needs? If not I can attempt to whip up something for refreshing a token.

**Comment by Ianyourgod** [comment]
Oh I didn't read enough. Besides my problem, I still have a couple of questions; What does the /login endpoint actually do? For the patch request, do I just use url params (?name=data)?

**Comment by Kenny2github** [comment]
`/login` is for programmatically going through the Scratch login process. It's normally not used because the point is usually for regular Scratch users to go through the Special:ScratchOAuth2 process.

`POST`, `PUT`, and `PATCH` requests have similar mechanics (but different semantics). All three take their information in the request body. (They could also take more information in query params, but that is not the case with SOA2.)

**Comment by Ianyourgod** [comment]
alright, thank you.
