### ISSUE TITLE
Problematic license

### ISSUE THREAD

**Issue by Steve0Greatness** [ScratchVerifier/ScratchOAuth2#72]
CC BY-NC-SA disallows commercial uses for all works that include ScratchOAuth2 in any way, shape, or form. Here are one primary reason why this is bad: all free software that makes use of this software is automatically non-free. One term of free software is that all free software must be usable for commercial purposes. As BY-NC-SA prohibits commercial uses, it may not be used by free software packages.

I ask that either:
* A notice that of the license of this software be added to the front page, and a notice of what it means for software.
* This software be licensed under a license that does not prohibit commercial use, like CC BY-SA, MIT, or CC BY.

**Comment by Kenny2github** [comment]
As far as I understand it, only the source code of this project is licensed under CC BY-NC-SA 4.0. So derivative works (i.e. modifications of the extension) cannot be commercial in nature. I'm not sure whether the unpublished source code of an otherwise publicly accessible MediaWiki installation which includes the extension would count as a derivative work. If so, that is a conflict of the nature you describe and might need an exception in the `LICENSE.txt`. For now, my opinion is that it would not count (and that the respective portions of the source code belonging to the extension and to MediaWiki proper would be under their separate licenses), but I'm open to being corrected with evidence. 

What's for sure is that the license does not prevent commercial projects from calling the APIs that the extension defines. My guess is that the applicable license there (i.e. the terms under which the returned data is licensed) is the license that applies to the content of the hosting wiki, or Scratch's CC BY-SA 2.0, possibly depending on where the data comes from. Apps that just use https://oauth2.scratch-wiki.info can use whatever license they want.

**Comment by Semisol** [comment]
*IANAL, all of the following is my own interpretation:*

For me, "commercial usage" requires the following:
1. there is a service or benefit obtained,
2. in exchange for any consideration with a monetary value,
3. where the service or benefit derives a substantial amount of the value from the codebase itself.

Some examples:
- Asking for donations without anything in return fails 1 and 3.
- Asking for donations with listing on a thank you page fails 3.
- Any product that isn't an authentication service (such as one just using SOA2 for signon) fails 3.

The license also should not apply to services using SOA2 APIs, as they do not incorporate any of the SOA2 code in their service (only calls to SOA2 APIs).

Either way, other licenses should be explored as CC licenses are not recommended for code.

**Comment by Kenny2github** [comment]
SOA2, to me, falls into a not-often-discussed category of software: software that powers a service, where there is only one widely-accepted instance of that service. This is the same category that, say, a username.github.io repository or a Discord bot's source might fall into.

My choice of CC BY-SA-NC was an intentional one, in contravention of the normal recommendation against its use for code, because I specifically wanted to exclude commercial use. I'm aware that that makes it non-FOSS.

That said, a license that is closer to the intent of what I want is probably the modified BSD-style license I invented for another repository of mine: https://github.com/Kenny2github/ButtonBot/blob/master/LICENSE
So maybe that's one option to explore. But for now it seems to me that the issue at hand is resolved.
